// Mocks generated by Mockito 5.4.6 from annotations
// in webapp/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i24;
import 'dart:ui' as _i25;

import 'package:dio/dio.dart' as _i27;
import 'package:flutter/material.dart' as _i23;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:stacked_services/stacked_services.dart' as _i21;
import 'package:webapp/core/model/get_user_model.dart' as _i3;
import 'package:webapp/core/model/login_model.dart' as _i2;
import 'package:webapp/services/api_service.dart' as _i26;
import 'package:webapp/ui/views/add_company/model/company_model.dart' as _i9;
import 'package:webapp/ui/views/banner/model/all_banner_model.dart' as _i19;
import 'package:webapp/ui/views/city/model/city_model.dart' as _i5;
import 'package:webapp/ui/views/contact_support/model/client_model.dart'
    as _i13;
import 'package:webapp/ui/views/influencers/model/influencers_model.dart'
    as _i8;
import 'package:webapp/ui/views/location_contact/models/location_contact_model.dart'
    as _i18;
import 'package:webapp/ui/views/permissions/model/get_permission_model.dart'
    as _i12;
import 'package:webapp/ui/views/plans/model/plans_model.dart' as _i6;
import 'package:webapp/ui/views/promote_projects/model/payment_split_model.dart'
    as _i17;
import 'package:webapp/ui/views/promote_projects/model/prmote_table_model.dart'
    as _i16;
import 'package:webapp/ui/views/promote_projects/model/promote_project_model.dart'
    as _i15;
import 'package:webapp/ui/views/report/model/report_model.dart' as _i20;
import 'package:webapp/ui/views/requests/model/request_model.dart' as _i14;
import 'package:webapp/ui/views/roles/model/roles_model.dart' as _i10;
import 'package:webapp/ui/views/services/model/service_model.dart' as _i7;
import 'package:webapp/ui/views/state/model/state_model.dart' as _i4;
import 'package:webapp/ui/views/sub_admin/model/sub_admin_model.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetUsersResponse_1 extends _i1.SmartFake
    implements _i3.GetUsersResponse {
  _FakeGetUsersResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStateModel_2 extends _i1.SmartFake implements _i4.StateModel {
  _FakeStateModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCityShowModel_3 extends _i1.SmartFake implements _i5.CityShowModel {
  _FakeCityShowModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlanModel_4 extends _i1.SmartFake implements _i6.PlanModel {
  _FakePlanModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceModel_5 extends _i1.SmartFake implements _i7.ServiceModel {
  _FakeServiceModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInfluencerModel_6 extends _i1.SmartFake
    implements _i8.InfluencerModel {
  _FakeInfluencerModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompanyModel_7 extends _i1.SmartFake implements _i9.CompanyModel {
  _FakeCompanyModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRolesModel_8 extends _i1.SmartFake implements _i10.RolesModel {
  _FakeRolesModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubAdminModel_9 extends _i1.SmartFake implements _i11.SubAdminModel {
  _FakeSubAdminModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPermissionModel_10 extends _i1.SmartFake
    implements _i12.GetPermissionModel {
  _FakeGetPermissionModel_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClientModel_11 extends _i1.SmartFake implements _i13.ClientModel {
  _FakeClientModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectRequestModel_12 extends _i1.SmartFake
    implements _i14.ProjectRequestModel {
  _FakeProjectRequestModel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectModel_13 extends _i1.SmartFake implements _i15.ProjectModel {
  _FakeProjectModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePromoteTableModel_14 extends _i1.SmartFake
    implements _i16.PromoteTableModel {
  _FakePromoteTableModel_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentSplitModel_15 extends _i1.SmartFake
    implements _i17.PaymentSplitModel {
  _FakePaymentSplitModel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationContactModel_16 extends _i1.SmartFake
    implements _i18.LocationContactModel {
  _FakeLocationContactModel_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllBannerModel_17 extends _i1.SmartFake
    implements _i19.AllBannerModel {
  _FakeAllBannerModel_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReportModel_18 extends _i1.SmartFake implements _i20.ReportModel {
  _FakeReportModel_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i21.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i22.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i22.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i23.GlobalKey<_i23.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i23.GlobalKey<_i23.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i21.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<T?>? navigateWithTransition<T>(
    _i23.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i23.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i21.Transition? transitionClass,
    _i21.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? replaceWithTransition<T>(
    _i23.Widget? page, {
    bool? opaque,
    String? transition = '',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i23.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i21.Transition? transitionClass,
    _i21.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i23.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i23.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? navigateToView<T>(
    _i23.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i23.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i21.Transition? transition,
    _i21.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i23.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? clearStackAndShowView<T>(
    _i23.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? clearTillFirstAndShowView<T>(
    _i23.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);

  @override
  _i24.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i23.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i24.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i21.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i21.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<_i21.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i24.Future<_i21.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i24.Future<_i21.SheetResponse<dynamic>?>.value(),
      ) as _i24.Future<_i21.SheetResponse<dynamic>?>);

  @override
  _i24.Future<_i21.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i25.Color? barrierColor = const _i25.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i24.Future<_i21.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i24.Future<_i21.SheetResponse<T>?>.value(),
      ) as _i24.Future<_i21.SheetResponse<T>?>);

  @override
  void completeSheet(_i21.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i21.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i21.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i23.Widget Function(
      _i23.BuildContext,
      _i21.DialogRequest<dynamic>,
      dynamic Function(_i21.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<_i21.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i25.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i25.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i23.RouteSettings? routeSettings,
    _i23.GlobalKey<_i23.NavigatorState>? navigatorKey,
    _i21.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i24.Future<_i21.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i24.Future<_i21.DialogResponse<dynamic>?>.value(),
      ) as _i24.Future<_i21.DialogResponse<dynamic>?>);

  @override
  _i24.Future<_i21.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i25.Color? barrierColor = const _i25.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i23.RouteSettings? routeSettings,
    _i23.GlobalKey<_i23.NavigatorState>? navigatorKey,
    _i23.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i24.Future<_i21.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i24.Future<_i21.DialogResponse<T>?>.value(),
      ) as _i24.Future<_i21.DialogResponse<T>?>);

  @override
  _i24.Future<_i21.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i25.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i25.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i23.RouteSettings? routeSettings,
    _i21.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i24.Future<_i21.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i24.Future<_i21.DialogResponse<dynamic>?>.value(),
      ) as _i24.Future<_i21.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i21.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i26.ApiService {
  @override
  _i24.Future<_i2.LoginResponse> loginAdmin(_i2.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginAdmin,
          [loginRequest],
        ),
        returnValue: _i24.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginAdmin,
            [loginRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginAdmin,
            [loginRequest],
          ),
        )),
      ) as _i24.Future<_i2.LoginResponse>);

  @override
  _i24.Future<dynamic> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i3.GetUsersResponse> getUsers({dynamic data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
          {#data: data},
        ),
        returnValue:
            _i24.Future<_i3.GetUsersResponse>.value(_FakeGetUsersResponse_1(
          this,
          Invocation.method(
            #getUsers,
            [],
            {#data: data},
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i3.GetUsersResponse>.value(_FakeGetUsersResponse_1(
          this,
          Invocation.method(
            #getUsers,
            [],
            {#data: data},
          ),
        )),
      ) as _i24.Future<_i3.GetUsersResponse>);

  @override
  _i24.Future<void> updateNotes({
    required int? userId,
    required String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNotes,
          [],
          {
            #userId: userId,
            #notes: notes,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i4.StateModel> addState(dynamic addStateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addState,
          [addStateRequest],
        ),
        returnValue: _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #addState,
            [addStateRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #addState,
            [addStateRequest],
          ),
        )),
      ) as _i24.Future<_i4.StateModel>);

  @override
  _i24.Future<List<_i4.Datum>> getStates() => (super.noSuchMethod(
        Invocation.method(
          #getStates,
          [],
        ),
        returnValue: _i24.Future<List<_i4.Datum>>.value(<_i4.Datum>[]),
        returnValueForMissingStub:
            _i24.Future<List<_i4.Datum>>.value(<_i4.Datum>[]),
      ) as _i24.Future<List<_i4.Datum>>);

  @override
  _i24.Future<_i4.StateModel> updateState(dynamic updateStateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateState,
          [updateStateRequest],
        ),
        returnValue: _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #updateState,
            [updateStateRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #updateState,
            [updateStateRequest],
          ),
        )),
      ) as _i24.Future<_i4.StateModel>);

  @override
  _i24.Future<_i4.StateModel> deleteState(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteState,
          [id],
        ),
        returnValue: _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #deleteState,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i4.StateModel>.value(_FakeStateModel_2(
          this,
          Invocation.method(
            #deleteState,
            [id],
          ),
        )),
      ) as _i24.Future<_i4.StateModel>);

  @override
  _i24.Future<List<_i5.Datum>> getCities() => (super.noSuchMethod(
        Invocation.method(
          #getCities,
          [],
        ),
        returnValue: _i24.Future<List<_i5.Datum>>.value(<_i5.Datum>[]),
        returnValueForMissingStub:
            _i24.Future<List<_i5.Datum>>.value(<_i5.Datum>[]),
      ) as _i24.Future<List<_i5.Datum>>);

  @override
  _i24.Future<_i5.CityShowModel> addCity(dynamic addCityRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCity,
          [addCityRequest],
        ),
        returnValue: _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #addCity,
            [addCityRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #addCity,
            [addCityRequest],
          ),
        )),
      ) as _i24.Future<_i5.CityShowModel>);

  @override
  _i24.Future<_i5.CityShowModel> updateCity(dynamic updateCityRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCity,
          [updateCityRequest],
        ),
        returnValue: _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #updateCity,
            [updateCityRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #updateCity,
            [updateCityRequest],
          ),
        )),
      ) as _i24.Future<_i5.CityShowModel>);

  @override
  _i24.Future<_i5.CityShowModel> deleteCity(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCity,
          [id],
        ),
        returnValue: _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #deleteCity,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i5.CityShowModel>.value(_FakeCityShowModel_3(
          this,
          Invocation.method(
            #deleteCity,
            [id],
          ),
        )),
      ) as _i24.Future<_i5.CityShowModel>);

  @override
  _i24.Future<_i6.PlanModel> getAllPlans() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlans,
          [],
        ),
        returnValue: _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #getAllPlans,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #getAllPlans,
            [],
          ),
        )),
      ) as _i24.Future<_i6.PlanModel>);

  @override
  _i24.Future<_i6.PlanModel> addPlan(dynamic addPlanRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlan,
          [addPlanRequest],
        ),
        returnValue: _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #addPlan,
            [addPlanRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #addPlan,
            [addPlanRequest],
          ),
        )),
      ) as _i24.Future<_i6.PlanModel>);

  @override
  _i24.Future<_i6.PlanModel> updatePlan(dynamic updatePlanRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlan,
          [updatePlanRequest],
        ),
        returnValue: _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #updatePlan,
            [updatePlanRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #updatePlan,
            [updatePlanRequest],
          ),
        )),
      ) as _i24.Future<_i6.PlanModel>);

  @override
  _i24.Future<_i6.PlanModel> deletePlan(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlan,
          [id],
        ),
        returnValue: _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #deletePlan,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i6.PlanModel>.value(_FakePlanModel_4(
          this,
          Invocation.method(
            #deletePlan,
            [id],
          ),
        )),
      ) as _i24.Future<_i6.PlanModel>);

  @override
  _i24.Future<_i7.ServiceModel> getAllService() => (super.noSuchMethod(
        Invocation.method(
          #getAllService,
          [],
        ),
        returnValue: _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #getAllService,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #getAllService,
            [],
          ),
        )),
      ) as _i24.Future<_i7.ServiceModel>);

  @override
  _i24.Future<_i7.ServiceModel> addService(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addService,
          [request],
        ),
        returnValue: _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #addService,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #addService,
            [request],
          ),
        )),
      ) as _i24.Future<_i7.ServiceModel>);

  @override
  _i24.Future<_i7.ServiceModel> updateService(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [request],
        ),
        returnValue: _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #updateService,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #updateService,
            [request],
          ),
        )),
      ) as _i24.Future<_i7.ServiceModel>);

  @override
  _i24.Future<_i7.ServiceModel> deleteService(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [id],
        ),
        returnValue: _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #deleteService,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i7.ServiceModel>.value(_FakeServiceModel_5(
          this,
          Invocation.method(
            #deleteService,
            [id],
          ),
        )),
      ) as _i24.Future<_i7.ServiceModel>);

  @override
  _i24.Future<void> getInfluencers() => (super.noSuchMethod(
        Invocation.method(
          #getInfluencers,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<dynamic> addInfluencer(_i27.FormData? formData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInfluencer,
          [formData],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i8.InfluencerModel> getAllInfluencer({dynamic data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllInfluencer,
          [],
          {#data: data},
        ),
        returnValue:
            _i24.Future<_i8.InfluencerModel>.value(_FakeInfluencerModel_6(
          this,
          Invocation.method(
            #getAllInfluencer,
            [],
            {#data: data},
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i8.InfluencerModel>.value(_FakeInfluencerModel_6(
          this,
          Invocation.method(
            #getAllInfluencer,
            [],
            {#data: data},
          ),
        )),
      ) as _i24.Future<_i8.InfluencerModel>);

  @override
  _i24.Future<void> addCompany(_i27.FormData? formData) => (super.noSuchMethod(
        Invocation.method(
          #addCompany,
          [formData],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i9.CompanyModel> getCompany() => (super.noSuchMethod(
        Invocation.method(
          #getCompany,
          [],
        ),
        returnValue: _i24.Future<_i9.CompanyModel>.value(_FakeCompanyModel_7(
          this,
          Invocation.method(
            #getCompany,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i9.CompanyModel>.value(_FakeCompanyModel_7(
          this,
          Invocation.method(
            #getCompany,
            [],
          ),
        )),
      ) as _i24.Future<_i9.CompanyModel>);

  @override
  _i24.Future<_i10.RolesModel> getAllRole() => (super.noSuchMethod(
        Invocation.method(
          #getAllRole,
          [],
        ),
        returnValue: _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #getAllRole,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #getAllRole,
            [],
          ),
        )),
      ) as _i24.Future<_i10.RolesModel>);

  @override
  _i24.Future<_i10.RolesModel> addRole(dynamic role) => (super.noSuchMethod(
        Invocation.method(
          #addRole,
          [role],
        ),
        returnValue: _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #addRole,
            [role],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #addRole,
            [role],
          ),
        )),
      ) as _i24.Future<_i10.RolesModel>);

  @override
  _i24.Future<_i10.RolesModel> deleteRole(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRole,
          [id],
        ),
        returnValue: _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #deleteRole,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i10.RolesModel>.value(_FakeRolesModel_8(
          this,
          Invocation.method(
            #deleteRole,
            [id],
          ),
        )),
      ) as _i24.Future<_i10.RolesModel>);

  @override
  _i24.Future<List<_i11.Datum>> getAllSubAdmin() => (super.noSuchMethod(
        Invocation.method(
          #getAllSubAdmin,
          [],
        ),
        returnValue: _i24.Future<List<_i11.Datum>>.value(<_i11.Datum>[]),
        returnValueForMissingStub:
            _i24.Future<List<_i11.Datum>>.value(<_i11.Datum>[]),
      ) as _i24.Future<List<_i11.Datum>>);

  @override
  _i24.Future<_i11.SubAdminModel> addSubAdmin(dynamic addSubAdminRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSubAdmin,
          [addSubAdminRequest],
        ),
        returnValue: _i24.Future<_i11.SubAdminModel>.value(_FakeSubAdminModel_9(
          this,
          Invocation.method(
            #addSubAdmin,
            [addSubAdminRequest],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i11.SubAdminModel>.value(_FakeSubAdminModel_9(
          this,
          Invocation.method(
            #addSubAdmin,
            [addSubAdminRequest],
          ),
        )),
      ) as _i24.Future<_i11.SubAdminModel>);

  @override
  _i24.Future<_i11.SubAdminModel> deleteSubAdmin(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSubAdmin,
          [id],
        ),
        returnValue: _i24.Future<_i11.SubAdminModel>.value(_FakeSubAdminModel_9(
          this,
          Invocation.method(
            #deleteSubAdmin,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i11.SubAdminModel>.value(_FakeSubAdminModel_9(
          this,
          Invocation.method(
            #deleteSubAdmin,
            [id],
          ),
        )),
      ) as _i24.Future<_i11.SubAdminModel>);

  @override
  _i24.Future<void> addPermissions(
    dynamic id,
    dynamic request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPermissions,
          [
            id,
            request,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i12.GetPermissionModel> getPermissions(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPermissions,
          [id],
        ),
        returnValue: _i24.Future<_i12.GetPermissionModel>.value(
            _FakeGetPermissionModel_10(
          this,
          Invocation.method(
            #getPermissions,
            [id],
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i12.GetPermissionModel>.value(
            _FakeGetPermissionModel_10(
          this,
          Invocation.method(
            #getPermissions,
            [id],
          ),
        )),
      ) as _i24.Future<_i12.GetPermissionModel>);

  @override
  _i24.Future<_i13.ClientModel> getAllContactSupport() => (super.noSuchMethod(
        Invocation.method(
          #getAllContactSupport,
          [],
        ),
        returnValue: _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #getAllContactSupport,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #getAllContactSupport,
            [],
          ),
        )),
      ) as _i24.Future<_i13.ClientModel>);

  @override
  _i24.Future<_i13.ClientModel> updateContactSupport(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContactSupport,
          [request],
        ),
        returnValue: _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #updateContactSupport,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #updateContactSupport,
            [request],
          ),
        )),
      ) as _i24.Future<_i13.ClientModel>);

  @override
  _i24.Future<_i13.ClientModel> deleteContactSupport(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteContactSupport,
          [request],
        ),
        returnValue: _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #deleteContactSupport,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i13.ClientModel>.value(_FakeClientModel_11(
          this,
          Invocation.method(
            #deleteContactSupport,
            [request],
          ),
        )),
      ) as _i24.Future<_i13.ClientModel>);

  @override
  _i24.Future<_i14.ProjectRequestModel> getClientRequest(
    dynamic request, {
    String? month,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientRequest,
          [request],
          {#month: month},
        ),
        returnValue: _i24.Future<_i14.ProjectRequestModel>.value(
            _FakeProjectRequestModel_12(
          this,
          Invocation.method(
            #getClientRequest,
            [request],
            {#month: month},
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i14.ProjectRequestModel>.value(
            _FakeProjectRequestModel_12(
          this,
          Invocation.method(
            #getClientRequest,
            [request],
            {#month: month},
          ),
        )),
      ) as _i24.Future<_i14.ProjectRequestModel>);

  @override
  _i24.Future<void> addPromoteNote(
    dynamic requestId,
    dynamic note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPromoteNote,
          [
            requestId,
            note,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> statusChange(dynamic request) => (super.noSuchMethod(
        Invocation.method(
          #statusChange,
          [request],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> waitingAccept(dynamic request) => (super.noSuchMethod(
        Invocation.method(
          #waitingAccept,
          [request],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> paymentStatusChange(dynamic request) => (super.noSuchMethod(
        Invocation.method(
          #paymentStatusChange,
          [request],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i14.ProjectRequestModel> clientReAssign(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #clientReAssign,
          [request],
        ),
        returnValue: _i24.Future<_i14.ProjectRequestModel>.value(
            _FakeProjectRequestModel_12(
          this,
          Invocation.method(
            #clientReAssign,
            [request],
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i14.ProjectRequestModel>.value(
            _FakeProjectRequestModel_12(
          this,
          Invocation.method(
            #clientReAssign,
            [request],
          ),
        )),
      ) as _i24.Future<_i14.ProjectRequestModel>);

  @override
  _i24.Future<dynamic> promoteProjectCreate(_i27.FormData? formData) =>
      (super.noSuchMethod(
        Invocation.method(
          #promoteProjectCreate,
          [formData],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i15.ProjectModel> getAllPromoteProjects(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPromoteProjects,
          [request],
        ),
        returnValue: _i24.Future<_i15.ProjectModel>.value(_FakeProjectModel_13(
          this,
          Invocation.method(
            #getAllPromoteProjects,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i15.ProjectModel>.value(_FakeProjectModel_13(
          this,
          Invocation.method(
            #getAllPromoteProjects,
            [request],
          ),
        )),
      ) as _i24.Future<_i15.ProjectModel>);

  @override
  _i24.Future<_i16.PromoteTableModel> getSubProjects(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubProjects,
          [request],
        ),
        returnValue:
            _i24.Future<_i16.PromoteTableModel>.value(_FakePromoteTableModel_14(
          this,
          Invocation.method(
            #getSubProjects,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i16.PromoteTableModel>.value(_FakePromoteTableModel_14(
          this,
          Invocation.method(
            #getSubProjects,
            [request],
          ),
        )),
      ) as _i24.Future<_i16.PromoteTableModel>);

  @override
  _i24.Future<dynamic> changePromoteStatus(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePromoteStatus,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> refundPromoteProject(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #refundPromoteProject,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i17.PaymentSplitModel> getPaymentSplit(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentSplit,
          [request],
        ),
        returnValue:
            _i24.Future<_i17.PaymentSplitModel>.value(_FakePaymentSplitModel_15(
          this,
          Invocation.method(
            #getPaymentSplit,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i17.PaymentSplitModel>.value(_FakePaymentSplitModel_15(
          this,
          Invocation.method(
            #getPaymentSplit,
            [request],
          ),
        )),
      ) as _i24.Future<_i17.PaymentSplitModel>);

  @override
  _i24.Future<dynamic> updatePaymentSplit(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePaymentSplit,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i15.ProjectModel> reAssignInf(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #reAssignInf,
          [request],
        ),
        returnValue: _i24.Future<_i15.ProjectModel>.value(_FakeProjectModel_13(
          this,
          Invocation.method(
            #reAssignInf,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i15.ProjectModel>.value(_FakeProjectModel_13(
          this,
          Invocation.method(
            #reAssignInf,
            [request],
          ),
        )),
      ) as _i24.Future<_i15.ProjectModel>);

  @override
  _i24.Future<_i18.LocationContactModel> getLocationContact() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationContact,
          [],
        ),
        returnValue: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #getLocationContact,
            [],
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #getLocationContact,
            [],
          ),
        )),
      ) as _i24.Future<_i18.LocationContactModel>);

  @override
  _i24.Future<_i18.LocationContactModel> createLocationContact(
          dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLocationContact,
          [request],
        ),
        returnValue: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #createLocationContact,
            [request],
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #createLocationContact,
            [request],
          ),
        )),
      ) as _i24.Future<_i18.LocationContactModel>);

  @override
  _i24.Future<_i18.LocationContactModel> deleteLocationContact(
          dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocationContact,
          [request],
        ),
        returnValue: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #deleteLocationContact,
            [request],
          ),
        )),
        returnValueForMissingStub: _i24.Future<_i18.LocationContactModel>.value(
            _FakeLocationContactModel_16(
          this,
          Invocation.method(
            #deleteLocationContact,
            [request],
          ),
        )),
      ) as _i24.Future<_i18.LocationContactModel>);

  @override
  _i24.Future<_i19.AllBannerModel> getAllBanner() => (super.noSuchMethod(
        Invocation.method(
          #getAllBanner,
          [],
        ),
        returnValue:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #getAllBanner,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #getAllBanner,
            [],
          ),
        )),
      ) as _i24.Future<_i19.AllBannerModel>);

  @override
  _i24.Future<_i19.AllBannerModel> createBanner(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBanner,
          [request],
        ),
        returnValue:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #createBanner,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #createBanner,
            [request],
          ),
        )),
      ) as _i24.Future<_i19.AllBannerModel>);

  @override
  _i24.Future<_i19.AllBannerModel> deleteBanner(dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBanner,
          [id],
        ),
        returnValue:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #deleteBanner,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i19.AllBannerModel>.value(_FakeAllBannerModel_17(
          this,
          Invocation.method(
            #deleteBanner,
            [id],
          ),
        )),
      ) as _i24.Future<_i19.AllBannerModel>);

  @override
  _i24.Future<_i20.ReportModel> getReport(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReport,
          [request],
        ),
        returnValue: _i24.Future<_i20.ReportModel>.value(_FakeReportModel_18(
          this,
          Invocation.method(
            #getReport,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i24.Future<_i20.ReportModel>.value(_FakeReportModel_18(
          this,
          Invocation.method(
            #getReport,
            [request],
          ),
        )),
      ) as _i24.Future<_i20.ReportModel>);

  @override
  _i24.Future<void> refundStatus(dynamic connectionId) => (super.noSuchMethod(
        Invocation.method(
          #refundStatus,
          [connectionId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<dynamic> getNotificationList() => (super.noSuchMethod(
        Invocation.method(
          #getNotificationList,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> deleteNotification(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotification,
          [ids],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> readNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #readNotification,
          [id],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> readAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #readAllNotifications,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> sendBroadcastNotification(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendBroadcastNotification,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> getAdminUserList(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdminUserList,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> storeTemplate(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeTemplate,
          [request],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> getTemplateList() => (super.noSuchMethod(
        Invocation.method(
          #getTemplateList,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> deleteTemplate(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTemplate,
          [id],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> getAttendance(
    String? month, {
    dynamic id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttendance,
          [month],
          {#id: id},
        ),
        returnValue: _i24.Future<dynamic>.value(),
        returnValueForMissingStub: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);
}
