// Mocks generated by Mockito 5.4.4 from annotations
// in webapp/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:dio/dio.dart' as _i15;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:stacked_services/stacked_services.dart' as _i9;
import 'package:webapp/core/model/get_profile_model.dart' as _i3;
import 'package:webapp/core/model/get_user_model.dart' as _i4;
import 'package:webapp/core/model/login_model.dart' as _i2;
import 'package:webapp/services/api_service.dart' as _i14;
import 'package:webapp/ui/views/city/model/city_model.dart' as _i6;
import 'package:webapp/ui/views/plans/model/plans_model.dart' as _i7;
import 'package:webapp/ui/views/services/model/service_model.dart' as _i8;
import 'package:webapp/ui/views/state/model/state_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAdminProfileResponse_1 extends _i1.SmartFake
    implements _i3.GetAdminProfileResponse {
  _FakeGetAdminProfileResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetUsersResponse_2 extends _i1.SmartFake
    implements _i4.GetUsersResponse {
  _FakeGetUsersResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStateModel_3 extends _i1.SmartFake implements _i5.StateModel {
  _FakeStateModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCityShowModel_4 extends _i1.SmartFake implements _i6.CityShowModel {
  _FakeCityShowModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlanModel_5 extends _i1.SmartFake implements _i7.PlanModel {
  _FakePlanModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServiceModel_6 extends _i1.SmartFake implements _i8.ServiceModel {
  _FakeServiceModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i9.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#previousRoute),
        ),
      ) as String);

  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#currentRoute),
        ),
      ) as String);

  @override
  _i11.GlobalKey<_i11.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i11.GlobalKey<_i11.NavigatorState>?);

  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i9.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<T?>? navigateWithTransition<T>(
    _i11.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i11.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i9.Transition? transitionClass,
    _i9.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? replaceWithTransition<T>(
    _i11.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i11.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i9.Transition? transitionClass,
    _i9.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void popUntil(
    _i11.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i11.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? navigateToView<T>(
    _i11.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i11.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i9.Transition? transition,
    _i9.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i11.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? clearStackAndShowView<T>(
    _i11.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? clearTillFirstAndShowView<T>(
    _i11.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);

  @override
  _i12.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i11.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i12.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i9.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i9.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i9.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i12.Future<_i9.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i12.Future<_i9.SheetResponse<dynamic>?>.value(),
      ) as _i12.Future<_i9.SheetResponse<dynamic>?>);

  @override
  _i12.Future<_i9.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i13.Color? barrierColor = const _i13.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i12.Future<_i9.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i12.Future<_i9.SheetResponse<T>?>.value(),
      ) as _i12.Future<_i9.SheetResponse<T>?>);

  @override
  void completeSheet(_i9.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i9.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i9.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i11.Widget Function(
      _i11.BuildContext,
      _i9.DialogRequest<dynamic>,
      dynamic Function(_i9.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i9.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i13.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i13.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i11.RouteSettings? routeSettings,
    _i11.GlobalKey<_i11.NavigatorState>? navigatorKey,
    _i9.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i12.Future<_i9.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i12.Future<_i9.DialogResponse<dynamic>?>.value(),
      ) as _i12.Future<_i9.DialogResponse<dynamic>?>);

  @override
  _i12.Future<_i9.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i13.Color? barrierColor = const _i13.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    _i11.RouteSettings? routeSettings,
    _i11.GlobalKey<_i11.NavigatorState>? navigatorKey,
    _i11.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i12.Future<_i9.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i12.Future<_i9.DialogResponse<T>?>.value(),
      ) as _i12.Future<_i9.DialogResponse<T>?>);

  @override
  _i12.Future<_i9.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i13.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i13.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i11.RouteSettings? routeSettings,
    _i9.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i12.Future<_i9.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i12.Future<_i9.DialogResponse<dynamic>?>.value(),
      ) as _i12.Future<_i9.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i9.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i14.ApiService {
  @override
  _i12.Future<_i2.LoginResponse> loginAdmin(_i2.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginAdmin,
          [loginRequest],
        ),
        returnValue: _i12.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginAdmin,
            [loginRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #loginAdmin,
            [loginRequest],
          ),
        )),
      ) as _i12.Future<_i2.LoginResponse>);

  @override
  _i12.Future<_i3.GetAdminProfileResponse> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i12.Future<_i3.GetAdminProfileResponse>.value(
            _FakeGetAdminProfileResponse_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i3.GetAdminProfileResponse>.value(
                _FakeGetAdminProfileResponse_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i12.Future<_i3.GetAdminProfileResponse>);

  @override
  _i12.Future<_i4.GetUsersResponse> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue:
            _i12.Future<_i4.GetUsersResponse>.value(_FakeGetUsersResponse_2(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i4.GetUsersResponse>.value(_FakeGetUsersResponse_2(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
      ) as _i12.Future<_i4.GetUsersResponse>);

  @override
  _i12.Future<_i5.StateModel> addState(dynamic addStateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addState,
          [addStateRequest],
        ),
        returnValue: _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #addState,
            [addStateRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #addState,
            [addStateRequest],
          ),
        )),
      ) as _i12.Future<_i5.StateModel>);

  @override
  _i12.Future<List<_i5.Datum>> getStates() => (super.noSuchMethod(
        Invocation.method(
          #getStates,
          [],
        ),
        returnValue: _i12.Future<List<_i5.Datum>>.value(<_i5.Datum>[]),
        returnValueForMissingStub:
            _i12.Future<List<_i5.Datum>>.value(<_i5.Datum>[]),
      ) as _i12.Future<List<_i5.Datum>>);

  @override
  _i12.Future<_i5.StateModel> updateState(dynamic updateStateRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateState,
          [updateStateRequest],
        ),
        returnValue: _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #updateState,
            [updateStateRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #updateState,
            [updateStateRequest],
          ),
        )),
      ) as _i12.Future<_i5.StateModel>);

  @override
  _i12.Future<_i5.StateModel> deleteState(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteState,
          [id],
        ),
        returnValue: _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #deleteState,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i5.StateModel>.value(_FakeStateModel_3(
          this,
          Invocation.method(
            #deleteState,
            [id],
          ),
        )),
      ) as _i12.Future<_i5.StateModel>);

  @override
  _i12.Future<List<_i6.Datum>> getCities() => (super.noSuchMethod(
        Invocation.method(
          #getCities,
          [],
        ),
        returnValue: _i12.Future<List<_i6.Datum>>.value(<_i6.Datum>[]),
        returnValueForMissingStub:
            _i12.Future<List<_i6.Datum>>.value(<_i6.Datum>[]),
      ) as _i12.Future<List<_i6.Datum>>);

  @override
  _i12.Future<_i6.CityShowModel> addCity(dynamic addCityRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCity,
          [addCityRequest],
        ),
        returnValue: _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #addCity,
            [addCityRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #addCity,
            [addCityRequest],
          ),
        )),
      ) as _i12.Future<_i6.CityShowModel>);

  @override
  _i12.Future<_i6.CityShowModel> updateCity(dynamic updateCityRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCity,
          [updateCityRequest],
        ),
        returnValue: _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #updateCity,
            [updateCityRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #updateCity,
            [updateCityRequest],
          ),
        )),
      ) as _i12.Future<_i6.CityShowModel>);

  @override
  _i12.Future<_i6.CityShowModel> deleteCity(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCity,
          [id],
        ),
        returnValue: _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #deleteCity,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i6.CityShowModel>.value(_FakeCityShowModel_4(
          this,
          Invocation.method(
            #deleteCity,
            [id],
          ),
        )),
      ) as _i12.Future<_i6.CityShowModel>);

  @override
  _i12.Future<_i7.PlanModel> getAllPlans() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlans,
          [],
        ),
        returnValue: _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #getAllPlans,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #getAllPlans,
            [],
          ),
        )),
      ) as _i12.Future<_i7.PlanModel>);

  @override
  _i12.Future<_i7.PlanModel> addPlan(dynamic addPlanRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlan,
          [addPlanRequest],
        ),
        returnValue: _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #addPlan,
            [addPlanRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #addPlan,
            [addPlanRequest],
          ),
        )),
      ) as _i12.Future<_i7.PlanModel>);

  @override
  _i12.Future<_i7.PlanModel> updatePlan(dynamic updatePlanRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlan,
          [updatePlanRequest],
        ),
        returnValue: _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #updatePlan,
            [updatePlanRequest],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #updatePlan,
            [updatePlanRequest],
          ),
        )),
      ) as _i12.Future<_i7.PlanModel>);

  @override
  _i12.Future<_i7.PlanModel> deletePlan(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlan,
          [id],
        ),
        returnValue: _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #deletePlan,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i7.PlanModel>.value(_FakePlanModel_5(
          this,
          Invocation.method(
            #deletePlan,
            [id],
          ),
        )),
      ) as _i12.Future<_i7.PlanModel>);

  @override
  _i12.Future<_i8.ServiceModel> getAllService() => (super.noSuchMethod(
        Invocation.method(
          #getAllService,
          [],
        ),
        returnValue: _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #getAllService,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #getAllService,
            [],
          ),
        )),
      ) as _i12.Future<_i8.ServiceModel>);

  @override
  _i12.Future<_i8.ServiceModel> addService(dynamic request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addService,
          [request],
        ),
        returnValue: _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #addService,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #addService,
            [request],
          ),
        )),
      ) as _i12.Future<_i8.ServiceModel>);

  @override
  _i12.Future<_i8.ServiceModel> updateService(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateService,
          [request],
        ),
        returnValue: _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #updateService,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #updateService,
            [request],
          ),
        )),
      ) as _i12.Future<_i8.ServiceModel>);

  @override
  _i12.Future<_i8.ServiceModel> deleteService(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteService,
          [id],
        ),
        returnValue: _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #deleteService,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i8.ServiceModel>.value(_FakeServiceModel_6(
          this,
          Invocation.method(
            #deleteService,
            [id],
          ),
        )),
      ) as _i12.Future<_i8.ServiceModel>);

  @override
  _i12.Future<void> getInfluencers() => (super.noSuchMethod(
        Invocation.method(
          #getInfluencers,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<dynamic> addInfluencer(_i15.FormData? formData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addInfluencer,
          [formData],
        ),
        returnValue: _i12.Future<dynamic>.value(),
        returnValueForMissingStub: _i12.Future<dynamic>.value(),
      ) as _i12.Future<dynamic>);

  @override
  _i12.Future<dynamic> updateInfluencer(_i15.FormData? formData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInfluencer,
          [formData],
        ),
        returnValue: _i12.Future<dynamic>.value(),
        returnValueForMissingStub: _i12.Future<dynamic>.value(),
      ) as _i12.Future<dynamic>);
}
